# Generated by Django 2.2.7 on 2019-11-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
    ]
