# Generated by Django 2.2.7 on 2019-11-28 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_myuuidmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
