# Generated by Django 2.2.7 on 2019-11-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employeemode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeMode',
        ),
    ]
