# Generated by Django 2.2.7 on 2019-12-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='updated',
        ),
    ]
