# Generated by Django 2.2.7 on 2019-12-02 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_common.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191202_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True)),
                ('conversation', django_common.db_fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'requested'), ('REJECTED', 'rejected'), ('ACCEPTED', 'accepted'), ('UNFRIEND', 'unfriend')], default='requested', max_length=50)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persnal_chat', to='core.PersonalChat')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requset_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
