# Generated by Django 2.2.7 on 2019-12-05 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_friend_personalchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persnal_chat', to='core.PersonalChat'),
        ),
    ]
