# Generated by Django 2.2.7 on 2019-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191205_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
